"""Implementation of the ``lemma control-plane`` CLI (Refs #25).

The Control Plane is the receiving end of ``lemma-agent forward``. It
accepts signed evidence envelopes via HTTP, verifies them against the
producer's public key, and persists them to a per-producer day file.

This slice ships ``serve`` only — aggregation, unified-graph build,
and policy push are tracked under #25 as separate slices.
"""

from __future__ import annotations

import json
import signal
import ssl
from dataclasses import asdict
from datetime import datetime
from http.server import ThreadingHTTPServer
from pathlib import Path

import typer
from rich.console import Console
from rich.table import Table

from lemma.services.control_plane import (
    aggregate,
    build_topology,
    compliance_rollup,
    make_handler_class,
    render_topology_dot,
)

console = Console()

control_plane_app = typer.Typer(
    name="control-plane",
    help="Federated Control Plane commands (receiver, aggregation, policy push).",
    no_args_is_help=True,
)

# Inlined deployment templates so the artifacts are always available (including
# from an installed wheel) and renderable with simple {{KEY}} substitution.
_SYSTEMD_TEMPLATE = """\
# Lemma Control Plane — systemd unit.
# Generated by `lemma control-plane install --shape systemd`.
# Install: sudo cp lemma-control-plane.service /etc/systemd/system/ \\
#   && sudo systemctl daemon-reload && sudo systemctl enable --now lemma-control-plane
[Unit]
Description=Lemma Control Plane receiver
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart={{BINARY}} control-plane serve --port {{PORT}} \\
  --evidence-dir {{EVIDENCE_DIR}} --keys-dir {{KEYS_DIR}} --bind {{BIND}}
Restart=on-failure
RestartSec=5
# Drop privileges and harden the unit; the receiver only needs its data dirs.
DynamicUser=yes
StateDirectory=lemma-control-plane
NoNewPrivileges=yes
ProtectSystem=strict
ProtectHome=yes

[Install]
WantedBy=multi-user.target
"""

_COMPOSE_TEMPLATE = """\
# Lemma Control Plane — docker-compose.
# Generated by `lemma control-plane install --shape docker-compose`.
# Run: docker compose up -d
services:
  lemma-control-plane:
    image: {{IMAGE}}
    command: >-
      control-plane serve --port {{PORT}}
      --evidence-dir {{EVIDENCE_DIR}} --keys-dir {{KEYS_DIR}} --bind 0.0.0.0
    ports:
      - "{{PORT}}:{{PORT}}"
    volumes:
      - cp-evidence:{{EVIDENCE_DIR}}
      - cp-keys:{{KEYS_DIR}}
    restart: unless-stopped

volumes:
  cp-evidence:
  cp-keys:
"""

# --- Helm chart (Refs #42 — "Kubernetes Helm chart deploys with helm install").
# Only values.yaml carries the connector's {{KEY}} placeholders; the templates
# use Helm's own {{ .Values.* }} syntax, which the {{KEY}} substitution leaves
# untouched (no bare {{PORT}}/{{IMAGE}}/... tokens appear in them).
_HELM_CHART_YAML = """\
apiVersion: v2
name: lemma-control-plane
description: Lemma Control Plane receiver — verifies and persists signed evidence envelopes.
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/JoshDoesIT/Lemma
"""

_HELM_VALUES_YAML = """\
# Values for the Lemma Control Plane chart.
# Generated by `lemma control-plane install --shape helm`.
replicaCount: 1

image:
  repository: "{{IMAGE}}"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: {{PORT}}

paths:
  evidenceDir: "{{EVIDENCE_DIR}}"
  keysDir: "{{KEYS_DIR}}"

persistence:
  enabled: true
  evidenceSize: 1Gi
  keysSize: 64Mi

resources: {}
"""

_HELM_HELPERS_TPL = """\
{{- define "lemma-control-plane.name" -}}
lemma-control-plane
{{- end -}}

{{- define "lemma-control-plane.labels" -}}
app.kubernetes.io/name: {{ include "lemma-control-plane.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end -}}
"""

_HELM_DEPLOYMENT_YAML = """\
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lemma-control-plane.name" . }}
  labels:
    {{- include "lemma-control-plane.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "lemma-control-plane.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "lemma-control-plane.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        fsGroup: 10001
      containers:
        - name: control-plane
          image: {{ .Values.image.repository }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            # readOnlyRootFilesystem is on below, so keep Python off the root FS.
            - name: PYTHONDONTWRITEBYTECODE
              value: "1"
            - name: PYTHONUNBUFFERED
              value: "1"
          args:
            - control-plane
            - serve
            - --port
            - "{{ .Values.service.port }}"
            - --evidence-dir
            - {{ .Values.paths.evidenceDir }}
            - --keys-dir
            - {{ .Values.paths.keysDir }}
            - --bind
            - 0.0.0.0
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: evidence
              mountPath: {{ .Values.paths.evidenceDir }}
            - name: keys
              mountPath: {{ .Values.paths.keysDir }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: evidence
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "lemma-control-plane.name" . }}-evidence
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: keys
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "lemma-control-plane.name" . }}-keys
          {{- else }}
          emptyDir: {}
          {{- end }}
"""

_HELM_SERVICE_YAML = """\
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lemma-control-plane.name" . }}
  labels:
    {{- include "lemma-control-plane.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "lemma-control-plane.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
"""

_HELM_PVC_YAML = """\
{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "lemma-control-plane.name" . }}-evidence
  labels:
    {{- include "lemma-control-plane.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.persistence.evidenceSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "lemma-control-plane.name" . }}-keys
  labels:
    {{- include "lemma-control-plane.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.persistence.keysSize }}
{{- end }}
"""

_HELM_NOTES_TXT = """\
Lemma Control Plane installed as release {{ .Release.Name }}.

The receiver accepts signed evidence envelopes at POST /v1/evidence.
Forward agent evidence to it — from your cluster:

  kubectl port-forward svc/{{ include "lemma-control-plane.name" . }} \
{{ .Values.service.port }}:{{ .Values.service.port }}
  lemma-agent forward --endpoint http://127.0.0.1:{{ .Values.service.port }}/v1/evidence

For production, front the Service with an Ingress terminating TLS and
enable mTLS on the receiver (see docs/security/evidence-and-transport.md).
"""

_CHART_DIR = "lemma-control-plane"
_HELM_FILES = {
    f"{_CHART_DIR}/Chart.yaml": _HELM_CHART_YAML,
    f"{_CHART_DIR}/values.yaml": _HELM_VALUES_YAML,
    f"{_CHART_DIR}/templates/_helpers.tpl": _HELM_HELPERS_TPL,
    f"{_CHART_DIR}/templates/deployment.yaml": _HELM_DEPLOYMENT_YAML,
    f"{_CHART_DIR}/templates/service.yaml": _HELM_SERVICE_YAML,
    f"{_CHART_DIR}/templates/pvc.yaml": _HELM_PVC_YAML,
    f"{_CHART_DIR}/templates/NOTES.txt": _HELM_NOTES_TXT,
}

# Each shape maps to the set of files it renders (relative path -> template).
_INSTALL_SHAPES: dict[str, dict[str, str]] = {
    "systemd": {"lemma-control-plane.service": _SYSTEMD_TEMPLATE},
    "docker-compose": {"docker-compose.yml": _COMPOSE_TEMPLATE},
    "helm": _HELM_FILES,
}


def _render(template: str, substitutions: dict[str, str]) -> str:
    body = template
    for key, value in substitutions.items():
        body = body.replace("{{" + key + "}}", value)
    return body


@control_plane_app.command(
    name="install",
    help="Render a Control Plane deployment artifact (systemd, docker-compose, or a Helm chart).",
)
def install_command(
    shape: str = typer.Option(
        ..., "--shape", help="Deployment shape: systemd, docker-compose, or helm."
    ),
    output: str = typer.Option(..., "--output", help="Output directory for the rendered artifact."),
    port: int = typer.Option(8443, "--port", help="Port the receiver listens on."),
    image: str = typer.Option(
        "ghcr.io/joshdoesit/lemma:latest",
        "--image",
        help="Container image (docker-compose shape only).",
    ),
    binary: str = typer.Option(
        "/usr/local/bin/lemma",
        "--binary",
        help="Path to the lemma binary on the host (systemd shape only).",
    ),
    evidence_dir: str = typer.Option(
        "/var/lib/lemma-control-plane/evidence", "--evidence-dir", help="Receiver evidence dir."
    ),
    keys_dir: str = typer.Option(
        "/var/lib/lemma-control-plane/keys", "--keys-dir", help="Producer public-keys dir."
    ),
    bind: str = typer.Option("127.0.0.1", "--bind", help="Bind address (systemd shape)."),
    force: bool = typer.Option(False, "--force", help="Overwrite an existing artifact."),
) -> None:
    """Render a Control Plane deployment artifact (Refs #42, Enterprise Deployment Options)."""
    if shape not in _INSTALL_SHAPES:
        console.print(
            f"[red]Error:[/red] unknown --shape {shape!r}; "
            f"valid shapes: {', '.join(sorted(_INSTALL_SHAPES))}."
        )
        raise typer.Exit(code=1)

    files = _INSTALL_SHAPES[shape]
    out_dir = Path(output)
    out_dir.mkdir(parents=True, exist_ok=True)

    targets = {rel: out_dir / rel for rel in files}
    existing = sorted(str(t) for t in targets.values() if t.exists())
    if existing and not force:
        console.print(f"[red]Error:[/red] {existing[0]} already exists; pass --force to overwrite.")
        raise typer.Exit(code=1)

    substitutions = {
        "PORT": str(port),
        "IMAGE": image,
        "BINARY": binary,
        "EVIDENCE_DIR": evidence_dir,
        "KEYS_DIR": keys_dir,
        "BIND": bind,
    }
    for rel, template in files.items():
        target = targets[rel]
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(_render(template, substitutions))

    if shape == "systemd":
        target = targets["lemma-control-plane.service"]
        console.print(f"[green]Wrote[/green] systemd Control Plane artifact to {target}")
        console.print(
            "Install with: [bold]sudo cp "
            + str(target)
            + " /etc/systemd/system/ && sudo systemctl daemon-reload && "
            + "sudo systemctl enable --now lemma-control-plane[/bold]"
        )
    elif shape == "docker-compose":
        target = targets["docker-compose.yml"]
        console.print(f"[green]Wrote[/green] docker-compose Control Plane artifact to {target}")
        console.print(f"Run with: [bold]docker compose -f {target} up -d[/bold]")
    else:  # helm
        chart = out_dir / _CHART_DIR
        console.print(f"[green]Wrote[/green] Helm chart ({len(files)} files) to {chart}")
        console.print(
            f"Install with: [bold]helm install lemma-control-plane {chart} "
            f"--set image.repository={image}[/bold]"
        )


@control_plane_app.command(
    name="serve",
    help=(
        "Run the Control Plane receiver. Accepts POSTed signed envelopes "
        "from `lemma-agent forward` and persists them per producer."
    ),
)
def serve_command(
    port: int = typer.Option(
        ...,
        "--port",
        help="TCP port to bind on 127.0.0.1.",
    ),
    evidence_dir: str = typer.Option(
        ...,
        "--evidence-dir",
        help="Directory under which the receiver writes <producer>/<YYYY-MM-DD>.jsonl files.",
    ),
    keys_dir: str = typer.Option(
        ...,
        "--keys-dir",
        help="Directory of producer public keys (subdirectories named after each producer).",
    ),
    cert: str = typer.Option(
        "",
        "--cert",
        help="PEM server certificate (enables HTTPS). Pair with --key.",
    ),
    key: str = typer.Option(
        "",
        "--key",
        help="PEM server private key (enables HTTPS). Pair with --cert.",
    ),
    client_ca: str = typer.Option(
        "",
        "--client-ca",
        help="PEM CA bundle that signs client certs — when set, the receiver requires mTLS.",
    ),
    bind: str = typer.Option(
        "127.0.0.1",
        "--bind",
        help="Bind address. Default 127.0.0.1; pass 0.0.0.0 to expose on all interfaces.",
    ),
    project_dir: str = typer.Option(
        "",
        "--project-dir",
        help=(
            "Lemma project root to serve as policy. When set, agents can "
            "GET /v1/policy to pull the project's frameworks/controls/scopes."
        ),
    ),
) -> None:
    if (cert and not key) or (key and not cert):
        console.print("[red]Error:[/red] --cert and --key must be set together (both or neither).")
        raise typer.Exit(code=1)
    if client_ca and not cert:
        console.print(
            "[red]Error:[/red] --client-ca requires --cert / --key (mTLS only "
            "makes sense over HTTPS)."
        )
        raise typer.Exit(code=1)

    evidence_path = Path(evidence_dir)
    keys_path = Path(keys_dir)
    evidence_path.mkdir(parents=True, exist_ok=True)
    keys_path.mkdir(parents=True, exist_ok=True)

    handler_cls = make_handler_class(
        evidence_dir=evidence_path,
        keys_dir=keys_path,
        project_dir=Path(project_dir) if project_dir else None,
    )
    server = ThreadingHTTPServer((bind, port), handler_cls)

    if cert:
        ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
        ctx.load_cert_chain(certfile=cert, keyfile=key)
        if client_ca:
            ctx.load_verify_locations(cafile=client_ca)
            ctx.verify_mode = ssl.CERT_REQUIRED
        server.socket = ctx.wrap_socket(server.socket, server_side=True)
        scheme = "https"
    else:
        scheme = "http"

    actual_port = server.server_address[1]
    console.print(
        f"[green]Lemma Control Plane[/green] listening on "
        f"{scheme}://{bind}:{actual_port}/v1/evidence (POST signed envelopes here)"
    )
    console.print(f"  evidence-dir: {evidence_path}")
    console.print(f"  keys-dir:     {keys_path}")
    if client_ca:
        console.print(f"  mTLS:         CERT_REQUIRED (CA={client_ca})")
    elif cert:
        console.print("  mTLS:         disabled (server cert only)")

    def _shutdown(_signo: int, _frame: object) -> None:
        console.print("[yellow]Lemma Control Plane shutting down.[/yellow]")
        server.shutdown()

    # signal.signal only works on the main thread; tests run the CLI
    # from a worker thread, so swallow the ValueError there.
    try:
        signal.signal(signal.SIGTERM, _shutdown)
        signal.signal(signal.SIGINT, _shutdown)
    except ValueError:
        pass
    try:
        server.serve_forever()
    finally:
        server.server_close()


def _isoformat(dt: datetime | None) -> str:
    return dt.isoformat() if dt is not None else ""


@control_plane_app.command(
    name="aggregate",
    help=(
        "Summarise persisted evidence across all producers (the unified "
        "compliance view). Pair with `serve` to inspect what's been received."
    ),
)
def aggregate_command(
    evidence_dir: str = typer.Option(
        ...,
        "--evidence-dir",
        help="Directory the receiver writes <producer>/<YYYY-MM-DD>.jsonl files to.",
    ),
    output: str = typer.Option(
        "",
        "--output",
        help="Write the rollup as JSON to PATH instead of printing a table.",
    ),
) -> None:
    state = aggregate(Path(evidence_dir))

    if output:
        # Convert dataclasses to JSON-friendly dicts; datetimes become
        # ISO 8601 strings so a downstream consumer can parse them
        # without bespoke decoders.
        payload = asdict(state)
        for key in ("first_signed_at", "last_signed_at"):
            payload[key] = _isoformat(payload[key])
        for prod in payload["producers"]:
            for key in ("first_signed_at", "last_signed_at"):
                prod[key] = _isoformat(prod[key])
        Path(output).write_text(json.dumps(payload, indent=2) + "\n")
        console.print(f"[green]Wrote[/green] aggregated rollup to {output}")
        return

    if state.producer_count == 0:
        console.print(f"[yellow]No producer evidence found under[/yellow] {evidence_dir}")
        return

    table = Table(title=f"Lemma Control Plane — {evidence_dir}")
    table.add_column("Producer", style="bold")
    table.add_column("Envelopes", justify="right")
    table.add_column("Day files", justify="right")
    table.add_column("First signed", style="dim")
    table.add_column("Last signed", style="dim")
    for p in state.producers:
        table.add_row(
            p.producer,
            str(p.envelope_count),
            str(p.day_file_count),
            _isoformat(p.first_signed_at),
            _isoformat(p.last_signed_at),
        )
    console.print(table)
    console.print(
        f"[bold]Total:[/bold] {state.total_envelopes} envelopes "
        f"across {state.producer_count} producers"
        + (f" ({state.parse_errors} parse errors)" if state.parse_errors else "")
    )


@control_plane_app.command(
    name="graph",
    help=(
        "Render the federation topology as Graphviz DOT or JSON — every "
        "producer's envelope chain in one view. Pair with `serve` and "
        "`aggregate` for the full Control Plane operator workflow."
    ),
)
def graph_command(
    evidence_dir: str = typer.Option(
        ...,
        "--evidence-dir",
        help="Directory the receiver writes <producer>/<YYYY-MM-DD>.jsonl files to.",
    ),
    output: str = typer.Option(
        "",
        "--output",
        help="Write the rendered graph to PATH instead of stdout.",
    ),
    fmt: str = typer.Option(
        "dot",
        "--format",
        help="Output format: dot (Graphviz) or json.",
    ),
) -> None:
    if fmt not in {"dot", "json"}:
        console.print(f"[red]Error:[/red] unknown --format {fmt!r}; valid: dot, json.")
        raise typer.Exit(code=1)

    topology = build_topology(Path(evidence_dir))

    if fmt == "dot":
        body = render_topology_dot(topology)
    else:
        payload = {
            "envelope_count": topology.envelope_count,
            "producers": [
                {
                    "producer": p.producer,
                    "chain": [
                        {
                            "entry_hash": e.entry_hash,
                            "prev_hash": e.prev_hash,
                            "signed_at": e.signed_at.isoformat(),
                        }
                        for e in p.chain
                    ],
                }
                for p in topology.producers
            ],
        }
        body = json.dumps(payload, indent=2) + "\n"

    if output:
        Path(output).write_text(body)
        console.print(f"[green]Wrote[/green] {fmt} topology graph to {output}")
    else:
        # `print` (not console.print) to avoid Rich's wrapping/escaping —
        # the DOT output needs to be byte-stable for Graphviz to parse.
        print(body, end="")


@control_plane_app.command(
    name="compliance",
    help=(
        "Render the compliance-state rollup keyed by (framework, control_id) "
        "across every producer's persisted findings — the unified compliance "
        "graph layer of the Control Plane (Refs #25)."
    ),
)
def compliance_command(
    evidence_dir: str = typer.Option(
        ...,
        "--evidence-dir",
        help="Directory the receiver writes <producer>/<YYYY-MM-DD>.jsonl files to.",
    ),
    output: str = typer.Option(
        "",
        "--output",
        help="Write the rollup as JSON to PATH instead of printing a table.",
    ),
) -> None:
    rollup = compliance_rollup(Path(evidence_dir))

    if output:
        payload = {
            "findings_total": rollup.findings_total,
            "controls_total": rollup.controls_total,
            "controls": [
                {
                    "framework": c.framework,
                    "control_id": c.control_id,
                    "verdicts": dict(c.verdicts),
                    "producers": sorted(c.producers),
                }
                for c in rollup.controls
            ],
        }
        Path(output).write_text(json.dumps(payload, indent=2) + "\n")
        console.print(f"[green]Wrote[/green] compliance rollup to {output}")
        return

    if rollup.controls_total == 0:
        console.print(
            "[yellow]No compliance findings found under[/yellow] "
            f"{evidence_dir}\n"
            "Pair `lemma agent evaluate` with `lemma-agent forward` to "
            "populate the receiver's evidence with signed findings."
        )
        return

    table = Table(title=f"Lemma Compliance Rollup — {evidence_dir}")
    table.add_column("Framework", style="bold")
    table.add_column("Control")
    table.add_column("Verdicts")
    table.add_column("Producers", style="dim")
    for c in rollup.controls:
        verdicts = ", ".join(f"{k}={v}" for k, v in sorted(c.verdicts.items()))
        producers = ", ".join(sorted(c.producers))
        table.add_row(c.framework, c.control_id, verdicts, producers)
    console.print(table)
    console.print(
        f"[bold]Total:[/bold] {rollup.findings_total} findings "
        f"across {rollup.controls_total} controls"
    )
