"""AI System Card — versioned AI transparency document.

Describes every AI model used in Lemma: what it does, what it can't do,
what data it was trained on, and how its outputs are governed.

This is the machine-readable counterpart to traditional "AI Ethics"
documentation, designed specifically for GRC engineers and auditors
who need to assess the reliability of AI-assisted compliance evidence.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class ModelCard(BaseModel):
    """Describes a single AI model used in the platform.

    Attributes:
        model_id: Model identifier (e.g., 'ollama/llama3.2').
        provider: Provider name (e.g., 'Ollama (local)', 'OpenAI').
        version: Model version string.
        purpose: What this model is used for in Lemma.
        capabilities: What the model can do well.
        limitations: Known failure modes and weaknesses.
        training_data: Description of training data provenance.
        model_hash: Optional integrity digest (e.g., ``sha256:...``) for
            supply-chain verification. Empty string when unavailable.
    """

    model_id: str
    provider: str
    version: str
    purpose: str
    capabilities: list[str] = Field(default_factory=list)
    limitations: list[str] = Field(default_factory=list)
    training_data: str = ""
    model_hash: str = ""


class AISystemCard(BaseModel):
    """Aggregate AI transparency document for the platform.

    Attributes:
        name: Document title.
        version: Document version.
        description: High-level description of AI usage.
        intended_use: What the AI system is designed for.
        out_of_scope: What the AI system should NOT be used for.
        risk_mitigations: Controls in place to manage AI risk.
        models: List of model cards for each AI model used.
    """

    name: str
    version: str
    description: str
    intended_use: str
    out_of_scope: list[str] = Field(default_factory=list)
    risk_mitigations: list[str] = Field(default_factory=list)
    models: list[ModelCard] = Field(default_factory=list)

    def render_markdown(self) -> str:
        """Render the system card as a human-readable markdown document.

        Returns:
            Markdown string suitable for display or export.
        """
        lines: list[str] = []

        lines.append(f"# {self.name}")
        lines.append("")
        lines.append(f"**Version:** {self.version}")
        lines.append("")
        lines.append("## Overview")
        lines.append("")
        lines.append(self.description)
        lines.append("")
        lines.append("## Intended Use")
        lines.append("")
        lines.append(self.intended_use)
        lines.append("")

        if self.out_of_scope:
            lines.append("## Out of Scope")
            lines.append("")
            lines.append(
                "The following uses are **explicitly out of scope** for Lemma's AI capabilities:"
            )
            lines.append("")
            for item in self.out_of_scope:
                lines.append(f"- {item}")
            lines.append("")

        if self.risk_mitigations:
            lines.append("## Risk Mitigations")
            lines.append("")
            for item in self.risk_mitigations:
                lines.append(f"- {item}")
            lines.append("")

        if self.models:
            lines.append("## Model Registry")
            lines.append("")
            for model in self.models:
                lines.append(f"### {model.model_id}")
                lines.append("")
                lines.append(f"- **Provider:** {model.provider}")
                lines.append(f"- **Version:** {model.version}")
                lines.append(f"- **Purpose:** {model.purpose}")
                if model.training_data:
                    lines.append(f"- **Training Data:** {model.training_data}")
                lines.append("")

                if model.capabilities:
                    lines.append("**Capabilities:**")
                    lines.append("")
                    for cap in model.capabilities:
                        lines.append(f"- {cap}")
                    lines.append("")

                if model.limitations:
                    lines.append("**Known Limitations:**")
                    lines.append("")
                    for lim in model.limitations:
                        lines.append(f"- {lim}")
                    lines.append("")

        lines.append("---")
        lines.append(
            "*This document is auto-generated by Lemma. "
            "For questions, see the project documentation.*"
        )
        lines.append("")

        return "\n".join(lines)


def get_default_system_card() -> AISystemCard:
    """Return the default Lemma AI System Card.

    Pre-populated with the models and governance controls
    that ship with Lemma out of the box.

    Returns:
        AISystemCard with default content.
    """
    return AISystemCard(
        name="Lemma AI Transparency Card",
        version="1.0.0",
        description=(
            "This document describes every AI model used in the Lemma GRC platform, "
            "their capabilities, known limitations, and the governance controls "
            "in place to ensure trustworthy AI-assisted compliance."
        ),
        intended_use=(
            "Lemma uses AI to accelerate compliance mapping by identifying semantic "
            "relationships between organizational policies and framework controls. "
            "AI outputs are always advisory — they require human review before "
            "becoming part of the compliance record."
        ),
        out_of_scope=[
            "Legal compliance determinations — Lemma does not provide legal advice",
            "Audit sign-off — AI outputs cannot substitute for qualified auditor judgment",
            "Regulatory enforcement decisions",
            "Autonomous control implementation without human review",
        ],
        risk_mitigations=[
            "All AI outputs enter PROPOSED state requiring explicit human review",
            "Rejection requires a mandatory rationale (enforced programmatically)",
            "Append-only trace log captures every AI decision with full context",
            "Confidence thresholds flag uncertain results as LOW_CONFIDENCE",
            "Model provenance tracked via model_id and version in every trace",
            "No customer data is sent to external APIs when using local models (Ollama)",
        ],
        models=[
            ModelCard(
                model_id="ollama/llama3.2",
                provider="Ollama (local)",
                version="3.2",
                purpose=(
                    "Control mapping — maps policy excerpts to framework controls "
                    "with confidence scores and natural language rationales"
                ),
                capabilities=[
                    "Semantic policy-to-control matching",
                    "Confidence scoring (0.0-1.0) for mapping quality",
                    "Natural language rationale generation",
                    "Runs locally — no data leaves the machine",
                ],
                limitations=[
                    "May hallucinate control relationships not supported by policy text",
                    "Not fine-tuned on domain-specific GRC/compliance data",
                    "Performance degrades on highly technical or niche frameworks",
                    "Context window limits may truncate long policy documents",
                    "Confidence scores are self-reported and may not correlate with accuracy",
                ],
                training_data=(
                    "Meta Llama 3.2 — trained on publicly available internet data. "
                    "No Lemma-specific fine-tuning has been applied."
                ),
            ),
            ModelCard(
                model_id="openai/gpt-4o-mini",
                provider="OpenAI (cloud)",
                version="2024-07-18",
                purpose="Control mapping (optional cloud backend)",
                capabilities=[
                    "Higher accuracy on complex policy language",
                    "Larger context window for long documents",
                    "Semantic policy-to-control matching with rationales",
                ],
                limitations=[
                    "Requires API key — data is sent to OpenAI servers",
                    "Subject to OpenAI's data retention and usage policies",
                    "API availability depends on external service",
                    "Cost per token may be significant at scale",
                ],
                training_data="OpenAI proprietary training data (not disclosed)",
            ),
        ],
    )
