package canonjson

import (
	"encoding/json"
	"testing"
)

// Each case's want value is the exact byte sequence Python's
//
//	json.dumps(value, sort_keys=True, separators=(",", ":"))
//
// produces. Generated by running the snippet inline; treat these
// strings as the parity oracle.
func TestMarshalRawMatchesPythonGolden(t *testing.T) {
	cases := []struct {
		name string
		in   string // JSON wire form, fed in via json.RawMessage
		want string
	}{
		{"empty_object", `{}`, `{}`},
		{"single_key", `{"a":1}`, `{"a":1}`},
		{"two_keys_unsorted", `{"b":1,"a":2}`, `{"a":2,"b":1}`},
		{"nested_array", `{"a":[1,2,3]}`, `{"a":[1,2,3]}`},
		{"nested_object_sorted", `{"a":{"y":2,"x":1}}`, `{"a":{"x":1,"y":2}}`},
		{"mixed_scalars",
			`{"s":"hello \"world\"","i":42,"f":1.5,"b":true,"n":null}`,
			`{"b":true,"f":1.5,"i":42,"n":null,"s":"hello \"world\""}`,
		},
		{"top_level_array", `[1,2,3]`, `[1,2,3]`},
		{"deeply_nested",
			`{"nested":{"deep":{"k":[{"a":1},{"b":2}]}}}`,
			`{"nested":{"deep":{"k":[{"a":1},{"b":2}]}}}`,
		},
		{"unicode_escape", `{"unicode":"café"}`, `{"unicode":"caf\u00e9"}`},
		{"empty_containers",
			`{"empty_list":[],"empty_obj":{}}`,
			`{"empty_list":[],"empty_obj":{}}`,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got, err := MarshalRaw(json.RawMessage(tc.in))
			if err != nil {
				t.Fatalf("MarshalRaw(%q) error: %v", tc.in, err)
			}
			if string(got) != tc.want {
				t.Errorf("MarshalRaw(%q)\n got:  %q\n want: %q", tc.in, got, tc.want)
			}
		})
	}
}

func TestMarshalRawPreservesIntegerNumbers(t *testing.T) {
	// OCSF events carry int fields like class_uid. Decoding them as
	// float64 corrupts canonical bytes (3 -> 3.0). Verify json.Number
	// path keeps them as integer text.
	in := `{"class_uid":2003,"time":1700000000}`
	want := `{"class_uid":2003,"time":1700000000}`
	got, err := MarshalRaw(json.RawMessage(in))
	if err != nil {
		t.Fatalf("MarshalRaw error: %v", err)
	}
	if string(got) != want {
		t.Errorf("got %q want %q", got, want)
	}
}

func TestMarshalRawPreservesFloatNumbers(t *testing.T) {
	in := `{"score":0.85,"big":10000000000.0}`
	want := `{"big":10000000000.0,"score":0.85}`
	got, err := MarshalRaw(json.RawMessage(in))
	if err != nil {
		t.Fatalf("MarshalRaw error: %v", err)
	}
	if string(got) != want {
		t.Errorf("got %q want %q", got, want)
	}
}

func TestMarshalRawEscapesControlCharacters(t *testing.T) {
	cases := []struct {
		name string
		in   string
		want string
	}{
		{"tab", `{"s":"a\tb"}`, `{"s":"a\tb"}`},
		{"newline", `{"s":"a\nb"}`, `{"s":"a\nb"}`},
		{"backslash", `{"s":"a\\b"}`, `{"s":"a\\b"}`},
		{"quote", `{"s":"a\"b"}`, `{"s":"a\"b"}`},
		{"control_01_unicode_escaped_input", `{"s":"a\u0001b"}`, `{"s":"a\u0001b"}`},
		{"forward_slash_unescaped", `{"s":"a/b"}`, `{"s":"a/b"}`},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got, err := MarshalRaw(json.RawMessage(tc.in))
			if err != nil {
				t.Fatalf("MarshalRaw error: %v", err)
			}
			if string(got) != tc.want {
				t.Errorf("got %q want %q", got, tc.want)
			}
		})
	}
}

func TestMarshalRawEscapesNonAsciiBmp(t *testing.T) {
	// Non-ASCII (> 0x7E) → \uXXXX (Python ensure_ascii=True default)
	in := `{"s":"café"}`
	want := `{"s":"caf\u00e9"}`
	got, err := MarshalRaw(json.RawMessage(in))
	if err != nil {
		t.Fatalf("MarshalRaw error: %v", err)
	}
	if string(got) != want {
		t.Errorf("got %q want %q", got, want)
	}
}

func TestMarshalRawEscapesSupplementaryPlaneWithSurrogates(t *testing.T) {
	// Codepoints > U+FFFF emit a UTF-16 surrogate pair in Python's
	// json.dumps (ensure_ascii=True). Emoji 😀 is U+1F600
	// → surrogate pair 😀.
	in := `{"s":"emoji😀"}`
	want := `{"s":"emoji\ud83d\ude00"}`
	got, err := MarshalRaw(json.RawMessage(in))
	if err != nil {
		t.Fatalf("MarshalRaw error: %v", err)
	}
	if string(got) != want {
		t.Errorf("got %q want %q", got, want)
	}
}

func TestMarshalRawRejectsInvalidJSON(t *testing.T) {
	_, err := MarshalRaw(json.RawMessage(`{not json`))
	if err == nil {
		t.Fatal("expected error on invalid JSON, got nil")
	}
}
