package crypto

import (
	"strings"
	"testing"
)

// Deterministic fixture: Ed25519 keypair from seed bytes(range(32)),
// signing the SHA-256 hex of a known entry hash. Generated by:
//
//	priv = Ed25519PrivateKey.from_private_bytes(bytes(range(32)))
//	priv.sign(bytes.fromhex(knownHashHex))
//
// (See plan: critical files / parity oracle.)
const (
	knownPubKeyPEM = `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAA6EHv/POEL4dcN0Y50vAmWfk1jCbpQ1fHdyGZBJVMbg=
-----END PUBLIC KEY-----
`
	knownHashHex      = "70199efb59c00012139c6498d6d6c387e901d77e81ecc39b4b76a4d2b4e8bc42"
	knownSignatureHex = "de4a21b1df63f6ad2b2a34ed5afea8c49d99b8e7d03405f285f827eaaffce04195132bf8938dc831471a2d6e256bd9499d5bc33bacdd09d259b2f6a78b4ba109"
)

func TestLoadPublicKeyAcceptsPKIXEd25519PEM(t *testing.T) {
	pub, err := LoadPublicKey([]byte(knownPubKeyPEM))
	if err != nil {
		t.Fatalf("LoadPublicKey returned error: %v", err)
	}
	if len(pub) != 32 {
		t.Errorf("expected 32-byte Ed25519 public key, got %d bytes", len(pub))
	}
}

func TestLoadPublicKeyRejectsMalformedPEM(t *testing.T) {
	_, err := LoadPublicKey([]byte("not a PEM"))
	if err == nil {
		t.Fatal("expected error on malformed PEM, got nil")
	}
}

func TestLoadPublicKeyRejectsEmptyInput(t *testing.T) {
	_, err := LoadPublicKey(nil)
	if err == nil {
		t.Fatal("expected error on empty input, got nil")
	}
}

func TestLoadPublicKeyRejectsNonEd25519Algorithm(t *testing.T) {
	// A real RSA SubjectPublicKeyInfo PEM — parses successfully, but the
	// loader must refuse anything that isn't Ed25519. Lemma only signs
	// evidence with Ed25519.
	rsaPEM := `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkSGdA6ZTKWo0z2eKNq7V
AOfuSScQfiN7cmil9xBeI4xW6K0gZjwOy8iFYwj93KNvcLB7tNQ++VQ2e8FTAmwU
rdZZCKY2qHjmggGC+fpJHG2RfB8iS3kTzF/XV+kWCiVvbRGWGOhEn7GQFXmb6nGZ
QSgcoxcndcorkUR8+84JPYBnUXkp6IOrvNuwPiq/qHAcGbj7OBvhLGc+SxWCkjL8
k6hMhLKlR2OKix0HGQshXO8iaUa/IbZxSZRk1Bt/P2GU0OUs/qmaSmxk+uR416ub
JB2XMqUE9q+kUg2a5RkCNx1ZxRDYKVmKwfvPgs4O8TwMwXpFmHLl19OHnMj+ZPk9
LwIDAQAB
-----END PUBLIC KEY-----
`
	_, err := LoadPublicKey([]byte(rsaPEM))
	if err == nil {
		t.Fatal("expected error on RSA public key, got nil")
	}
	if !strings.Contains(err.Error(), "ed25519") &&
		!strings.Contains(err.Error(), "Ed25519") {
		t.Errorf("error should mention Ed25519, got: %v", err)
	}
}

func TestVerifyEntryHashAcceptsKnownGoodSignature(t *testing.T) {
	pub, err := LoadPublicKey([]byte(knownPubKeyPEM))
	if err != nil {
		t.Fatalf("LoadPublicKey: %v", err)
	}
	if !VerifyEntryHash(pub, knownHashHex, knownSignatureHex) {
		t.Error("VerifyEntryHash rejected a known-good signature")
	}
}

func TestVerifyEntryHashRejectsTamperedSignature(t *testing.T) {
	pub, err := LoadPublicKey([]byte(knownPubKeyPEM))
	if err != nil {
		t.Fatalf("LoadPublicKey: %v", err)
	}
	// Flip the first hex char: 'd' -> 'e'
	bad := "e" + knownSignatureHex[1:]
	if VerifyEntryHash(pub, knownHashHex, bad) {
		t.Error("VerifyEntryHash accepted a tampered signature")
	}
}

func TestVerifyEntryHashRejectsTamperedEntryHash(t *testing.T) {
	pub, err := LoadPublicKey([]byte(knownPubKeyPEM))
	if err != nil {
		t.Fatalf("LoadPublicKey: %v", err)
	}
	bad := "8" + knownHashHex[1:] // flip leading nibble 7 -> 8
	if VerifyEntryHash(pub, bad, knownSignatureHex) {
		t.Error("VerifyEntryHash accepted a hash that was not the one signed")
	}
}

func TestVerifyEntryHashReturnsFalseOnMalformedHex(t *testing.T) {
	pub, err := LoadPublicKey([]byte(knownPubKeyPEM))
	if err != nil {
		t.Fatalf("LoadPublicKey: %v", err)
	}
	if VerifyEntryHash(pub, "not hex", knownSignatureHex) {
		t.Error("VerifyEntryHash should reject non-hex entry hash")
	}
	if VerifyEntryHash(pub, knownHashHex, "not hex") {
		t.Error("VerifyEntryHash should reject non-hex signature")
	}
}
