/** Cross-language entry-hash parity (Refs #108).
 *
 * Proves the TS chain-hash primitive is byte-identical to Python's
 * `sha256(prev_hash + json.dumps(payload, sort_keys=True, separators=(",",":")))`.
 * The fixture's `expectedEntryHash` was generated by Python; a matching Python
 * test (tests/sdk/test_ts_interop.py) checks the same fixture from the other
 * side, so both languages independently agree on the value.
 */

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { test } from "node:test";

import { chainHash } from "../src/evidence.ts";

const fixturePath = fileURLToPath(new URL("./fixtures/entry-hash.json", import.meta.url));
const fixture = JSON.parse(readFileSync(fixturePath, "utf8"));

test("TS chainHash matches the Python-generated entry hash", () => {
  const got = chainHash(fixture.prevHash, fixture.payload);
  assert.equal(got, fixture.expectedEntryHash);
});
